### PR TITLE
Update README.md with Docker Run option

### PR DESCRIPTION
**Pull request by Jafner**

### CODE REVIEW

**Comment by Uzay-G** [comment]
could you remove the # contributors section here, I decided it was redundant.

Also, do you think you could explain the possibility of using the images from docker hub (https://hub.docker.com/repository/registry-1.docker.io/uzayg/archivy/). This was recently set up so for now the latest release is not yet published but it'll be up there soon.

**Comment by Uzay-G** [comment]
This looks really good :tada:

**Comment by Jafner** [comment]
I'd prefer to wait on switching to a dockerhub image until we have an automated build flow setup. 
Once that's up, I'll include info for both methods. It will be trivial to update the documentation once we have a reliable automated image deployment workflow.

**Comment by Uzay-G** [comment]
Ok no problem.

**Pull request merged**
